# Generated by Django 2.2.2 on 2019-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190628_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
