# Generated by Django 2.2.2 on 2019-07-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img',
            new_name='image',
        ),
    ]
